# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/RCDesktopUI.csproj'
  buildPlatform: 'Any CPU'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$/RCDesktopUI/packages.config'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '**\RCDesktopUI.csproj'
    msbuildArgs: '/p:Platform=AnyCPU /p:OutputPath=Build'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'